### PR TITLE
Updated Artipie fronted to v0.0.4 + enabled github support

### PR DESCRIPTION
**Pull request by ChGen**
Updated Artipie fronted to v0.0.4 + enabled github support.
Try to login with your github account first.
https://central.artipie.com/signin

### CODE REVIEW

**Comment by ChGen** [comment]
@olenagerasimova , please review

**Comment by olenagerasimova** [comment]
@ChGen thanks, I've tried to login, it worked, but I found, [fixed bug](https://github.com/artipie/front/pull/87) with username in case of github login and release fron 0.0.5 versions. Could you please increase front version again?

**Comment by ChGen** [comment]
> @ChGen thanks, I've tried to login, it worked, but I found and [fixed bug](https://github.com/artipie/front/pull/87) with username in case of github login and release front 0.0.5 versions. Could you please increase front version again?

Ok, I'll update in this PR.

**Comment by ChGen** [comment]
@olenagerasimova , please check

**Comment by olenagerasimova** [comment]
@ChGen the problem is in the format of the artipie.yaml and ee-yaml we use to parse yamls: front uses eo-yaml 6.0.1 and it understands the following mappings in sequence formatting:
```yaml
credentials:
    - type: file
      path: _credentials.yml
    - type: github
```
Artipie uses eo-yaml 5, it only understands the following format with extra new lines:
```yaml
credentials:
    - 
      type: file
      path: _credentials.yml
    - 
      type: github
```
I [tried to update eo-yaml in Artipie](https://github.com/artipie/artipie/pull/1029), but it leads to other bugs and a lot of changes and does not look as a good idea because of these changes. So I'd say, let's better reformat artipie.yaml...

**Comment by ChGen** [comment]
> 

OMG, ok, I'll reformat  artipie.yaml and let you now.

**Comment by ChGen** [comment]
Fixed some issues, now it depends on https://github.com/artipie/artipie/issues/1032

**Comment by olenagerasimova** [comment]
@ChGen thanks, merging

**Pull request merged**
