### PR TITLE
Allow .svg file to be in the repositories

### PR DESCRIPTION
**Pull request by ChGen**
Allow .svg file to be in the repositories.

### CODE REVIEW

**Comment by ChGen** [comment]
@olenagerasimova , please review

**Comment by olenagerasimova** [comment]
@ChGen thanks, is it ok that all checks failed?

**Comment by ChGen** [comment]
@olenagerasimova , I don't remember this check statuses before. I remember it get deployed only after merge to master.

**Comment by ChGen** [comment]
@olenagerasimova , I removed some folders with incorrect permissions and check passed.

**Comment by olenagerasimova** [comment]
@ChGen great, merging

**Pull request merged**
