### PR TITLE
 New Artipie frontend support

### PR DESCRIPTION
**Pull request by ChGen**
Updated server & scripts to new versions of artipie & artipie/front.
GitHub auth. component currently doesn't work with new frontend, but builds & runs correctly.
https://artipie.com/
https://central.artipie.com/signin
Old artipie/frontend branch with required scripts was prepared too, for backup purposes:
https://github.com/artipie/central/tree/old-frontend

### CODE REVIEW

**Comment by ChGen** [comment]
It's deploying now with docker-compose on the same server as runner.

**Comment by ChGen** [comment]
@olenagerasimova , please review.

**Review by olenagerasimova — APPROVED** [review]
@ChGen thanks, LGTM. Also, new front version will be released tomorrow with github auth, we will be able to check how it works.

@dgarus please, take a look

**Review by dgarus — APPROVED** [review]
thanks!
LGTM

**Pull request merged**
